#include <iostream>

uintptr_t dwClientState;
uintptr_t dwClientState_State;
uintptr_t dwClientState_MaxPlayer;
uintptr_t dwClientState_ViewAngles;
uintptr_t dwppDirect3DDevice9;
uintptr_t dwEntityList;
uintptr_t dwLocalPlayer;
uintptr_t dwGlowObjectManager;
uintptr_t dwForceAttack;
uintptr_t dwForceForward;
uintptr_t dwForceBackward;
uintptr_t dwForceRight;
uintptr_t dwForceLeft;
uintptr_t dwForceJump;
uintptr_t m_vecOrigin;
uintptr_t m_iHealth;
uintptr_t m_vecViewOffset;
uintptr_t m_dwBoneMatrix;
uintptr_t m_iTeamNum;
uintptr_t m_iGlowIndex;
uintptr_t m_aimPunchAngle;
uintptr_t m_iShotsFired;
uintptr_t m_iCrosshairId;
uintptr_t m_iFOV;
uintptr_t m_bDormant;
uintptr_t m_hActiveWeapon;
uintptr_t m_iItemDefinitionIndex;
